### ISSUE TITLE
WOW!!

### ISSUE THREAD

**Issue by ghost** [EBSmash/gfn#1]
THIS IS THE BEST REPO EVER, IM GOING TO PING EVERYONE IN 10 SERVERS TO TELL EVERYONE TO WATCH, FORK, STAR, MAKE ISSUES, PULL REQUESTS AND TO TELL EVERYONE TO SHARE IT WITH THEIR ENTIRE FAMILY INCLUDING THEIR %TH COUSIN 2ND REMOVED. THIS WILL BE THE MOST POPULAR GITHUB REPOSITORY OF ALL TIME!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

😂  sorry

**Comment by EBSmash** [comment]
OMG SOMEONE FINALLY IS APPRECIAREING MY WORKl!!!!!>!>!>!>! THIS TOOK ME 68 YEARS TO CODE AND IT GOT NO RECOGNII+TION ): BUT NOW IM HAPYYYY! THANK YOU SMOKERBEAR12!!!!

**Comment by ghost** [comment]
WOEW THATS ACTUALLY SO BASED ANND AEWSOME THATS SO 😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎 🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶
